Repository WillofSteel-Devs/app, pull requests merged in 2024-06, with the labels that each got.

#12 GH-11: Add exceptions to backend
  backend/__init__.py
  backend/api.py
  backend/exceptions.py
  backend/route.py
  models/player.py
Labels: awaiting merge, type-feature

#14 GH-11: Add exceptions to backend (merge with feature/backend)
  backend/api.py
  backend/exceptions.py
Labels: awaiting merge

#15 Backend complete - Merge feature/backend into main
  .github/workflows/lint.yml
  backend.py
  backend/__init__.py
  backend/api.py
  backend/route.py
  gui/components/buttons.py
  gui/sidebar.py
  models/__init__.py
  models/alliance.py
  models/characteristics.py
  models/order.py
  models/player.py
  models/units.py
Labels: awaiting core review, skip issue

#18 GH-17 - Add API Key sidebar tab + API key box and label
  gui/app.py
  gui/components/buttons.py
  gui/components/inputs.py
  gui/components/labels.py
  gui/frames/api_key.py
  gui/sidebar.py
Labels: awaiting merge, type-security, type-feature, priority: 0 - critical

#21 GH-NA: Add backend checks for API
  backend/api.py
  gui/app.py
  gui/components/labels.py
  gui/frames/api_key.py
  requirements.txt
Labels: type-security, type-feature, skip issue

#25 GH-8: Added recruiting and associated backend
  .gitignore
  backend/api.py
  gui/components/buttons.py
  gui/components/dropdowns.py
  gui/frames/api_key.py
  gui/frames/recruitment.py
  main.pyw
Labels: awaiting merge

#32 GH-24: Implement Alliance Managment Frame
  backend/api.py
  gui/app.py
  gui/components/inputs.py
  gui/components/labels.py
  gui/frames/alliance.py
  gui/frames/api_key.py
  gui/sidebar.py
Labels: awaiting merge

#34 GH-31: Added Empty Frame on App Init
  gui/app.py
  gui/frames/empty_frame.py
Labels: awaiting merge

#35 Sync changes to main to construction branch
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  backend/api.py
  gui/app.py
  gui/components/inputs.py
  gui/components/labels.py
  gui/frames/alliance.py
  gui/frames/api_key.py
  gui/frames/empty_frame.py
  gui/sidebar.py
Labels: awaiting review

#36 GH-7: Implement Construction Frame
  backend/api.py
  gui/frames/construction.py
Labels: awaiting merge

#37 GH-7: Provide coroutine in SubmitButton instead of return value
  gui/frames/construction.py
Labels: awaiting merge, type-bug

#38 GH-33: Improve frontend
  gui/components/labels.py
  gui/frames/alliance.py
  gui/frames/api_key.py
  gui/frames/attack.py
  gui/frames/construction.py
  gui/frames/empty_frame.py
  gui/frames/lookup.py
  gui/frames/npc.py
  gui/frames/recruitment.py
Labels: awaiting core review, type-feature

#39 GH-30: Implement outposts frame
  backend/api.py
  gui/app.py
  gui/components/buttons.py
  gui/components/containers.py
  gui/components/popups.py
  gui/frames/outposts.py
  gui/sidebar.py
Labels: awaiting merge

#45 GH-23: Market functionality/menu
  backend/api.py
  gui/app.py
  gui/frames/market.py
  gui/sidebar.py
  models/order.py
Labels: awaiting core review, type-feature

#46 GH-5: Add NPC Menu
  backend/api.py
  gui/frames/npc.py
  models/__init__.py
  models/player.py
  models/results.py
Labels: awaiting core review, type-feature

#53 GH-44: Added update data functions instead of re-initializing new class
  backend/api.py
  gui/frames/alliance.py
  gui/frames/construction.py
  gui/sidebar.py
Labels: awaiting core review, type-feature

#59 GH-47: Fix API key frame label not covering full screen
  backend/api.py
  gui/app.py
  gui/components/labels.py
  gui/frames/alliance.py
  gui/frames/api_key.py
  gui/frames/construction.py
  gui/frames/empty_frame.py
  gui/frames/market.py
  gui/frames/npc.py
  gui/frames/outposts.py
  gui/sidebar.py
  models/__init__.py
  models/player.py
  models/results.py
  setup.py
Labels: awaiting merge

#60 GH-49: Fix NPC text overlap and add comma formating
  gui/frames/api_key.py
  gui/frames/npc.py
Labels: awaiting merge, priority: 0 - critical

#61 GH-52: Implement outpost capture
  gui/components/inputs.py
  gui/components/popups.py
  gui/frames/outposts.py
Labels: awaiting core review

#64 GH-63: Fixed troop names in the NPC frame.
  gui/components/labels.py
  gui/frames/npc.py
Labels: awaiting merge
